import { jsonResponse } from "@/lib/api-response";
import {
  publicModelMeshDiagnostics,
  publicProviderInfo,
} from "@/lib/providers";
import { publicImprovementPolicy } from "@/lib/improvement-policy";
import { TANKBENCH_CONTRACT_VERSION } from "@/lib/tankbench";
import { TANKAI_MASTER_PROMPT_VERSION } from "@/lib/tankai-master-prompt";
import { evaluatePublicReadiness, TANKAI_WEB_RELEASE } from "@/lib/public-readiness";
import { currentRuntimeBindings } from "@/lib/request-context";

export const dynamic = "force-dynamic";

export async function GET() {
  const providers = publicProviderInfo();
  const readiness = evaluatePublicReadiness(currentRuntimeBindings());
  return jsonResponse({
    product: "TankAI Web",
    release: TANKAI_WEB_RELEASE,
    promptVersion: TANKAI_MASTER_PROMPT_VERSION,
    runtimeOnline: readiness.runtimeOnline,
    applicationReady: readiness.applicationReady,
    core: readiness.applicationReady ? "ready" : "blocked",
    modelAccess: providers.length > 0 ? "active" : "not-configured",
    providers,
    modelMesh: publicModelMeshDiagnostics(),
    modes: {
      fast: { maxModelCalls: 1 },
      team: { maxModelCalls: 5 },
      deep: { maxModelCalls: 7 },
    },
    tankBenchContract: TANKBENCH_CONTRACT_VERSION,
    deploymentControl: {
      reactControlPlane: true,
      providerFallbacks: 3,
      circuitBreakerStates: ["closed", "open", "half_open"],
      manualCanaryTraffic: true,
      requestAttemptReceipts: true,
      promptAndResponsePlaintextPersisted: false,
    },
    reliabilityOperations: {
      admissionControl: true,
      defaultRateLimitPerMinute: 60,
      defaultMaximumConcurrency: 4,
      defaultInflightLeaseSeconds: 180,
      persistentInflightLeases: true,
      sloSnapshots: true,
      defaultSloWindowMinutes: 60,
      defaultMinimumRequests: 20,
      defaultMinimumSuccessRateBps: 9900,
      defaultMaximumP95LatencyMs: 5000,
      deduplicatedAlerts: true,
      deadLetterReplayRequiresFreshToolLease: true,
      redactedAuditExport: true,
      toolInputPlaintextExported: false,
    },
    dataControl: {
      contractVersion: "1.0.0",
      registeredUserDatasets: 55,
      transactionalExportSnapshot: true,
      perDatasetSha256: true,
      payloadSha256: true,
      ephemeralCredentialsExported: false,
      deletionConfirmationRequired: true,
      deletionGraceHours: 24,
      accountFrozenDuringDeletion: true,
      deletionReceiptStoresUserIdentifier: false,
      postDeletionDatabaseVerification: true,
      externalInfrastructureCoveredByReceipt: false,
    },
    improvement: publicImprovementPolicy(),
    persistence: "D1",
    goals: {
      durable: true,
      resumableState: true,
      eventReceipts: true,
      optimisticConcurrency: true,
      automaticExecutionResume: false,
    },
    projectSpaces: {
      durable: true,
      versionedTextDocuments: true,
      csvTableDocuments: true,
      csvDelimiters: [",", ";"],
      csvMaximumRows: 500,
      csvMaximumColumns: 50,
      csvMaximumCellCharacters: 2_000,
      spreadsheetFormulaInjectionBlocked: true,
      csvColumnProfiles: true,
      csvNullAndTypeStatistics: true,
      csvMaximumQueryFilters: 5,
      csvMaximumQuerySorts: 2,
      csvMaximumQueryColumns: 8,
      csvMaximumQueryRows: 10,
      csvMaximumQueryAggregations: 8,
      csvAggregationOperations: ["sum", "minimum", "maximum", "average"],
      csvAggregationNumericOnly: true,
      csvAggregationEmptyCells: "excluded",
      csvQueryReceipts: true,
      csvQueryFactsVerified: false,
      csvCodeExecution: false,
      immutableDocumentHistory: true,
      optimisticConcurrency: true,
      promptInjectionBoundary: "untrusted-project-data",
      maximumDocumentBytes: 24_000,
      binaryObjectStorage: "not-configured",
    },
    memory: {
      durable: true,
      types: ["episodic", "semantic", "procedural"],
      embeddingModel: "tank-hash-v1",
      embeddingDimensions: 192,
      retrieval: "tenant-scoped-cosine-ranking",
      feedbackPromotion: true,
      verificationStates: [
        "observed",
        "candidate",
        "confirmed",
        "disputed",
        "revoked",
      ],
      retention: ["hot", "warm", "cold", "deleted"],
      promptInjectionBoundary: "untrusted-recalled-memory",
    },
    capabilityLeases: {
      durable: true,
      requiredForModelRuns: true,
      immutableEvents: true,
      maximumDurationMinutes: 1_440,
      maximumUses: 20,
      scopes: ["account", "project"],
    },
    toolJobs: {
      durable: true,
      explicitLeaseRequired: true,
      tools: [
        "text.sha256",
        "text.analyze",
        "json.validate",
        "memory.retention",
        "web.fetch",
        "project.document.inspect",
        "code.patch.inspect",
      ],
      deterministicOnly: false,
      externalNetwork: "restricted-https-fetch",
      networkPolicy: {
        protocols: ["https"],
        credentials: "omit",
        redirects: "manual-revalidation",
        maximumRedirects: 3,
        timeoutMs: 10_000,
        maximumResponseBytes: 28_000,
        privateAddressLiteralsBlocked: true,
        localHostnameShapesBlocked: true,
        applicationEgressPolicy: "deny-by-default-allowlist",
        allowlistConfiguredBy: "TANKAI_EGRESS_ALLOWED_HOSTS",
        denylistConfiguredBy: "TANKAI_EGRESS_DENIED_HOSTS",
        denyTakesPrecedence: true,
        redirectPolicyRevalidation: true,
        dnsRebindingProtection: false,
        generalReleaseReady: false,
      },
      documentInspection: "tenant-and-project-scoped",
      patchInspection: "static-only",
      codeExecution: false,
      webSearch: false,
      multiSourceResearch: {
        available: true,
        providerSearch: false,
        explicitSourceUrlsRequired: true,
        minimumSources: 2,
        maximumSources: 4,
        minimumDistinctHosts: 2,
        verificationStatus: "unverified-source-observations",
        durablePerSourceReceipts: true,
      },
      idempotentCreation: true,
      optimisticClaims: true,
      staleClaimRecoveryMinutes: 5,
      workerClaimLeaseSeconds: 90,
      automaticRetryBackoff: true,
      deadLetterState: true,
      maximumAttempts: 3,
      immutableEvents: true,
      progressStreaming: {
        transport: "authenticated-sse",
        source: "immutable-tool-job-events",
        resumableCursor: "job-version-and-event-id",
        streamWindowSeconds: 15,
        reconnectMilliseconds: 1_500,
        inputAndOutputIncluded: false,
        executionStatusOnly: true,
        factsVerified: false,
      },
    },

    react: {
      durableRuns: true,
      states: [
        "ready",
        "running",
        "waiting_tool",
        "verifying",
        "completed",
        "failed",
        "cancelled",
        "budget_exhausted",
      ],
      privateReasoningStored: false,
      persistedDecisionSummaries: true,
      leaseProtectedToolActions: true,
      hashedObservations: true,
      maximumSteps: 32,
      maximumModelCalls: 64,
      maximumToolActions: 32,
      optimisticConcurrency: true,
      immutableEvents: true,
    },
    commander: {
      durableRuns: true,
      coupledToReAct: true,
      autonomousTransitionsPerRequest: 8,
      modelCapabilityLeaseRequired: true,
      modelCapabilityUsePerDecisionOrReview: 1,
      serverResolvedToolLeases: true,
      unleasedActionsExecuted: false,
      mandatoryCriticBeforeFinal: true,
      privateReasoningStored: false,
      rawModelResponsesStored: false,
      hashedModelResponses: true,
      maximumCycles: 24,
      maximumModelCalls: 20,
      maximumReviewCalls: 16,
      statuses: [
        "ready",
        "running",
        "waiting_tool",
        "reviewing",
        "completed",
        "failed",
        "cancelled",
        "budget_exhausted",
        "model_unavailable",
      ],
    },
    tankBench: {
      durableSuites: true,
      frozenCaseHashes: true,
      commanderEvidenceOnly: true,
      deterministicAssertions: true,
      weightedBaselineComparison: true,
      promotionRequiresPositiveGate: true,
      requiredCaseFailuresAllowed: 0,
      safetyCaseFailuresAllowed: 0,
      canaryTrafficStages: [5, 25, 50, 100],
      automaticRollback: true,
      immutableEvents: true,
    },
    workers: {
      durableIdentities: true,
      rawTokensStored: false,
      bearerAuthentication: true,
      statuses: ["active", "draining", "revoked"],
      maximumConcurrencyPerWorker: 4,
      claimHeartbeatExtensionSeconds: 90,
    },
    authentication: "Sign in with ChatGPT",
  });
}
