import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import ts from "../node_modules/typescript/lib/typescript.js";

const root=path.resolve(import.meta.dirname,"..");
function migrations(db){let count=0;for(const file of fs.readdirSync(path.join(root,"drizzle")).filter((name)=>/^\d{4}_.+\.sql$/u.test(name)).sort()){const source=fs.readFileSync(path.join(root,"drizzle",file),"utf8");for(const statement of source.split("--> statement-breakpoint").map((value)=>value.trim()).filter(Boolean)){db.exec(`${statement};`);count+=1;}}return count;}
class D1Prepared{constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args;}bind(...args){return new D1Prepared(this.db,this.sql,args);}async first(){return this.db.prepare(this.sql).get(...this.args)??null;}async all(){return{results:this.db.prepare(this.sql).all(...this.args)};}runSync(){const result=this.db.prepare(this.sql).run(...this.args);return{success:true,meta:{changes:Number(result.changes)}};}async run(){return this.runSync();}}
class D1DatabaseMock{constructor(db){this.db=db;}prepare(sql){return new D1Prepared(this.db,sql);}async batch(statements){const results=[];this.db.exec("BEGIN IMMEDIATE");try{for(const statement of statements)results.push(statement.runSync());this.db.exec("COMMIT");return results;}catch(error){this.db.exec("ROLLBACK");throw error;}}}
function transpile(file){return ts.transpileModule(fs.readFileSync(path.join(root,file),"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;}
function loadRuntime(db,providers){const module={exports:{}};const d1=new D1DatabaseMock(db);new Function("require","module","exports",transpile("lib/deployment-controller.ts"))((specifier)=>{if(specifier==="@/lib/request-context")return{currentRuntimeBindings:()=>({DB:d1})};if(specifier==="@/lib/providers")return{configuredProviders:()=>providers};if(specifier==="@/lib/tankbench-runtime")return{recordTankBenchCanaryObservation:async()=>({})};if(specifier==="@/lib/tankbench-suite-runner")return{resolveTankBenchRelease:async()=>({selectedReleaseId:"release-active",selectedLabel:"active",bucket:7,canaryPercent:0,source:"active"})};if(specifier==="@/lib/operations-runtime"){class OperationsRuntimeError extends Error{constructor(message,status,code){super(message);this.status=status;this.code=code;}}return{OperationsRuntimeError,acquireDeploymentAdmission:async({requestId,projectId})=>({id:requestId,projectId,expiresAt:null,managed:false}),releaseDeploymentAdmission:async()=>{},evaluateDeploymentSlo:async()=>({})};}throw new Error(`Unexpected import ${specifier}`);},module,module.exports);return module.exports;}
function seed(db){const now=new Date().toISOString();const userId="deploy-user";const projectId="11111111-1111-4111-8111-111111111111";db.prepare("INSERT INTO projects (id,user_id,name,description,status,version,content_revision,created_at,updated_at) VALUES (?,?,?,'','active',1,0,?,?)").run(projectId,userId,"Deployment",now,now);db.prepare("INSERT INTO tankbench_suites (id,user_id,project_id,name,description,status,case_count,suite_sha256,version,created_at,updated_at,frozen_at) VALUES ('suite',?,?,?,'','frozen',1,?,1,?,?,?)").run(userId,projectId,"Suite","a".repeat(64),now,now,now);db.prepare("INSERT INTO tankbench_runs (id,suite_id,user_id,project_id,baseline_label,candidate_label,status,min_score_delta_bps,max_regressions,baseline_score_bps,candidate_score_bps,delta_bps,regression_count,required_failure_count,safety_failure_count,version,created_at,updated_at,evaluated_at,completed_at) VALUES ('run','suite',?,?, 'base','candidate','passed',0,0,9000,9500,500,0,0,0,1,?,?,?,?)").run(userId,projectId,now,now,now,now);for(const [id,label,status,traffic] of [["release-active","active","active",100],["release-canary","canary","canary",5]])db.prepare("INSERT INTO tankbench_releases (id,source_run_id,user_id,project_id,label,status,traffic_percent,max_error_rate_bps,max_p95_latency_ms,min_stage_observations,stage_observation_offset,observation_count,error_count,version,created_at,updated_at,promoted_at) VALUES (?,'run',?,?,?,?,?,1000,5000,20,0,0,0,1,?,?,?)").run(id,userId,projectId,label,status,traffic,now,now,status==="active"?now:null);return{userId,projectId};}

test("React control plane falls back, opens circuits, traces attempts and resets safely",async()=>{const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");assert.equal(migrations(db),252);const ids=seed(db);let primaryCalls=0;let fallbackCalls=0;const providers=[{id:"primary",family:"test",name:"Primary",model:"p",priority:1,roles:[],async complete(){primaryCalls+=1;throw new Error("primary down");}},{id:"fallback",family:"test",name:"Fallback",model:"f",priority:2,roles:[],async complete(){fallbackCalls+=1;return{text:"fallback ok",latencyMs:12};}}];const runtime=loadRuntime(db,providers);const config=await runtime.configureDeploymentRelease({...ids,releaseId:"release-active",providerId:"primary",fallbackProviderIds:["fallback"],maxOutputTokens:1024,failureThreshold:1,recoveryTimeoutSeconds:300,halfOpenSuccesses:1});assert.deepEqual(config.fallbackProviderIds,["fallback"]);const request={instructions:"test",messages:[{role:"user",content:"hello"}],maxOutputTokens:100,safetyIdentifier:ids.userId};const first=await runtime.executeDeploymentRequest({...ids,routingKey:"stable-user",request});assert.equal(first.providerId,"fallback");assert.equal(first.attemptCount,2);assert.equal(primaryCalls,1);assert.equal(fallbackCalls,1);assert.equal(db.prepare("SELECT state FROM deployment_circuit_breakers WHERE provider_id='primary'").get().state,"open");const attempts1=db.prepare("SELECT status,provider_id FROM deployment_request_attempts ORDER BY attempt_ordinal").all();assert.deepEqual(attempts1.map((row)=>[row.status,row.provider_id]),[["failed","primary"],["succeeded","fallback"]]);const second=await runtime.executeDeploymentRequest({...ids,routingKey:"stable-user",request});assert.equal(second.providerId,"fallback");assert.equal(primaryCalls,1);assert.equal(fallbackCalls,2);const latest=db.prepare("SELECT id FROM deployment_requests ORDER BY created_at DESC,id DESC LIMIT 1").get();const attempts2=db.prepare("SELECT status,provider_id FROM deployment_request_attempts WHERE request_id=? ORDER BY attempt_ordinal").all(latest.id);assert.deepEqual(attempts2.map((row)=>[row.status,row.provider_id]),[["skipped_open","primary"],["succeeded","fallback"]]);const breaker=db.prepare("SELECT * FROM deployment_circuit_breakers WHERE provider_id='primary'").get();const reset=await runtime.resetDeploymentCircuit({userId:ids.userId,releaseId:"release-active",providerId:"primary",expectedVersion:Number(breaker.version)});assert.equal(reset.state,"closed");assert.equal(reset.consecutiveFailures,0);const state=await runtime.listDeploymentState(ids);assert.equal(state.recentRequests.length,2);assert.equal(state.recentRequests[0].attempts.length,2);assert.equal(state.metrics[0].requests,2);assert.equal(db.prepare("SELECT COUNT(*) AS total FROM deployment_control_events WHERE event_type='fallback_used'").get().total,2);assert.deepEqual(db.prepare("PRAGMA foreign_key_check").all(),[]);});

test("Manual canary traffic is versioned and can return to TankBench automatic routing",async()=>{const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");migrations(db);const ids=seed(db);const runtime=loadRuntime(db,[]);let traffic=await runtime.setDeploymentTraffic({...ids,releaseId:"release-canary",trafficPercent:42});assert.equal(traffic.enabled,true);assert.equal(traffic.trafficPercent,42);traffic=await runtime.setDeploymentTraffic({...ids,releaseId:"release-canary",trafficPercent:50,expectedVersion:traffic.version});assert.equal(traffic.version,2);traffic=await runtime.clearDeploymentTraffic({...ids,expectedVersion:traffic.version});assert.equal(traffic.enabled,false);assert.equal(db.prepare("SELECT COUNT(*) AS total FROM deployment_control_events WHERE event_type IN ('traffic_shifted','traffic_automatic')").get().total,3);});
