import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const project = new URL("../", import.meta.url);

test("master prompt is concrete, versioned, and has no template placeholders", async () => {
  const prompt = await readFile(
    new URL("docs/TANKAI_MASTERPROMPT.md", project),
    "utf8",
  );
  assert.ok(prompt.length > 20_000);
  assert.match(prompt, /Version: 2\.1\.0/);
  assert.match(prompt, /<web_product_contract>/);
  assert.match(prompt, /<owned_model_contract>/);
  assert.match(prompt, /<failure_corrections>/);
  assert.doesNotMatch(prompt, /\{\{[A-Z_]+\}\}/);
});

test("master plan defines a real web release and owned model gates", async () => {
  const plan = await readFile(
    new URL("docs/TANKAI_MASTERPLAN.md", project),
    "utf8",
  );
  assert.match(plan, /Version: 5\.3\.0/);
  assert.match(plan, /TankAI Web v0\.5\.0/);
  assert.match(plan, /Tank Router/);
  assert.match(plan, /Tank Critic/);
  assert.match(plan, /Tank Core/);
  assert.match(plan, /Kein Frontier-Pretrain ohne Startgate/);
  assert.match(plan, /Definition of Done für das Gesamtprojekt/);
  assert.match(plan, /TankAI Web v0\.30\.0/);
  assert.match(plan, /höchstens zwei eindeutige Gruppenspalten/);
  assert.match(plan, /TankAI Web v0\.31\.0/);
  assert.match(plan, /höchstens drei eindeutige Häufigkeitsspalten/);
  assert.match(plan, /höchstens zehn Buckets pro Spalte/);
  assert.match(plan, /festen 40\.000-Byte-Ausgabebudgets/);
  assert.match(plan, /TankAI Web v0\.32\.0/);
  assert.match(plan, /zwischen zwei und zwölf angeforderte Buckets/);
  assert.match(plan, /degeneriert markierten Einzelbucket/);
  assert.match(plan, /TankAI Web v0\.33\.0/);
  assert.match(plan, /verbindliche R7-Interpolation/);
  assert.match(plan, /ein bis neun eindeutige Wahrscheinlichkeiten/);
  assert.match(plan, /TankAI Web v0\.34\.0/);
  assert.match(plan, /Tukey-Fences/);
  assert.match(plan, /höchstens 20 deterministisch/);
  assert.match(plan, /TankAI Web v0\.35\.0/);
  assert.match(plan, /Nenner `N−1`/);
  assert.match(plan, /Ein-Pass-Berechnung nach Welford/);
  assert.match(plan, /TankAI Web v0\.36\.0/);
  assert.match(plan, /paarweiser vollständiger Fallausschluss/);
  assert.match(plan, /bivariate Ein-Pass-Berechnung nach Welford/);
  assert.match(plan, /Korrelation ausdrücklich als undefiniert/);
  assert.match(plan, /TankAI Web v0\.37\.0/);
  assert.match(plan, /verbindliche Gleichung `y = intercept \+ slope × x`/);
  assert.match(plan, /Freiheitsgrade `n−2`/);
  assert.match(plan, /höchstens 20 zeilenstabile Residuen/);
  assert.match(plan, /TankAI Web v0\.38\.0/);
  assert.match(plan, /extrapolation-low/);
  assert.match(plan, /residual-standard-error-leverage-1sigma/);
  assert.match(plan, /TankAI Web v0\.39\.0/);
  assert.match(plan, /zweiseitiger Kritikalwert aus der Student-t-Verteilung/);
  assert.match(plan, /Konfidenzintervall der mittleren Antwort/);
  assert.match(plan, /TankAI Web v0\.40\.0/);
  assert.match(plan, /intern studentisiertes Residuum/);
  assert.match(plan, /doppelten mittleren Leverage/);
  assert.match(plan, /TankAI Web v0\.41\.0/);
  assert.match(plan, /Cook-Distanz/);
  assert.match(plan, /Dᵢ > 4\/n/);
  assert.match(plan, /TankAI Web v0\.42\.0/);
  assert.match(plan, /PRESS-Quadratsumme/);
  assert.match(plan, /R²_pred = 1 − PRESS\/SST/);
  assert.match(plan, /höchstens fünf gewöhnliche Tabellenzeilen/);
  assert.match(plan, /TankAI Web v0\.43\.0/);
  assert.match(plan, /gelöschte Residuenquadratsumme/);
  assert.match(plan, /extern studentisiertes Residuum/);
  assert.match(plan, /DFFITS-Einflussdiagnostik/);
  assert.match(plan, /R1\.1 – ehrliche Receipts und Improvement Control/);
  assert.match(plan, /TankAI Web v0\.6\.0/);
  assert.match(plan, /TankAI Web v0\.7\.0/);
  assert.match(plan, /optimistische Zielversionen/);
  assert.match(plan, /TankAI Web v0\.8\.0/);
  assert.match(plan, /versionierten Text-\/Markdown-\/JSON-/);
  assert.match(plan, /Prompt-Injection-Datengrenze/);
  assert.match(plan, /TankAI Web v0\.9\.0/);
  assert.match(plan, /Capability Leases/);
  assert.match(plan, /atomarer Run-Bindung/);
  assert.match(plan, /TankAI Web v0\.10\.0/);
  assert.match(plan, /episodischen, semantischen und/);
  assert.match(plan, /Feedback-Promotion/);
  assert.match(plan, /TankAI Web v0\.11\.0/);
  assert.match(plan, /Tool Execution Leases/);
  assert.match(plan, /Claim-Tokens/);
  assert.match(plan, /Heartbeat-basierte Recovery/);
  assert.match(plan, /TankAI Web v0\.12\.0/);
  assert.match(plan, /kontrolliertes `web\.fetch`/);
  assert.match(plan, /project\.document\.inspect/);
  assert.match(plan, /code\.patch\.inspect/);
  assert.match(plan, /DNS-Rebinding/);
  assert.match(plan, /TankAI Web v0\.22\.0/);
  assert.match(plan, /unverified-source-observations/);
  assert.match(plan, /TankAI Web v0\.23\.0/);
  assert.match(plan, /authentifizierter SSE-Stream/);
  assert.match(plan, /TankAI Web v0\.24\.0/);
  assert.match(plan, /55 explizit registrierte/);
  assert.match(plan, /anonymisierter Löschbeleg/);
  assert.match(plan, /TankAI Web v0\.13\.0/);
  assert.match(plan, /Worker Runtime/);
  assert.match(plan, /TankAI Web v0\.14\.0/);
  assert.match(plan, /ReAct-Orchestrierung/);
  assert.match(plan, /privater Gedankengänge/);
  assert.match(plan, /TankAI Web v0\.15\.0/);
  assert.match(plan, /Commander-Orchestrierung/);
  assert.match(plan, /verpflichtende Critic-Prüfung/);
  assert.match(plan, /TankAI Web v0\.16\.0/);
  assert.match(plan, /TankBench-Promotion/);
  assert.match(plan, /automatischer Rollback/);
  assert.match(plan, /TankAI Web v0\.20\.0/);
  assert.match(plan, /Reliability & Operations/);
  assert.match(plan, /Admission Control/);
  assert.match(plan, /Dead-Letter-Replay/);
  assert.match(plan, /redigierter Audit-Export/);
  assert.match(plan, /TankAI Web v0\.27\.0/);
  assert.match(plan, /Public-Release-Bereitschaft/);
  assert.match(plan, /externer\s+Deployment-Verifier/);
  assert.match(plan, /TankAI Web v0\.28\.0/);
  assert.match(plan, /Cloudflare-Deploymentpfad/);
  assert.match(plan, /Deployment Receipt/);
});
